### ISSUE TITLE
Some guidelines in "Error Types" and "Error Wrapping" are incorrect

### ISSUE THREAD

**Issue by peterbourgon** [uber-go/guide#132]
> - Wrapped errors using "pkg/errors".Wrap

Since Go 1.13, wrapping errors is canonically done with fmt.Errorf and %w.

Relatedly, in the Error wrapping section,

```go
return fmt.Errorf("new store: %v", err)
```

should probably use %w instead of %v — or, if %v was intentional, should describe when to use %v vs. %w.

—

> Do the clients need to detect and handle this error? If so, you should use a custom type, and implement the Error() method.

Custom types are appropriate only when consumers need extra information about the error beyond it's identity. If consumers only need to handle the error by identity, then the more appropriate choice is a sentinel error, i.e. `var ErrFoo = errors.New("...")`. [ref](http://peter.bourgon.org/blog/2019/09/11/programming-with-errors.html)

—

> Be careful with exporting custom error types directly since they become part of the public API of the package. It is preferable to expose matcher functions to check the error instead.

It's true that both exported sentinel errors and error types become part of your package API, but the same is true of the matcher function suggested here, and they both have ~equivalent impact on API compatibility. What's more, the consequent advice to return unexported error types e.g.

```go
type errNotFound struct {
  file string
}
```

is surely incorrect, because the extra information captured in the type is inaccessible to callers. (In fact, it's almost always an error to return an unexported type from an exported function or method.)

**Comment by mway** [comment]
Thanks for flagging. We've intended to do this but were originally waiting until (1) error wrapping had been seen in the wild a bit more and (2) 1.13+ had been upgraded more broadly. Clearly those two criteria have been met at this point. ;)

> the consequent advice to return unexported error types [...] is surely incorrect, because the extra information captured in the type is inaccessible to callers

There are, of course, situations in which the error nuances are irrelevant to callers but the disambiguation is valuable within the package itself. The (probably) more common case is exporting error types so we can check is-a error relationships (and perhaps leverage the semantics of inner errors, etc).

I think it's important to be clear on the point that error types should NOT export data fields, otherwise they'd be mutable (and instead to export methods that expose the underlying information).

> In fact, it's almost always an error to return an unexported type from an exported function or method.

Yep. In fairness, however, I think a more common case is to do something like:

```go
type myError struct { /* ... */ }

func doSomething() error {
  return myError{
    // ...
  }
}
```

which is absolutely valid, if not limited in usefulness.

**Comment by peterbourgon** [comment]
> Clearly those two criteria have been met at this point. ;)

😎 

—

> I think it's important to be clear on the point that error types should NOT export data fields, otherwise they'd be mutable (and instead one should export methods that expose the underlying information).

If you're saying that

```go
type DataError struct {
    problem int
    inner   error
}

func (e *DataError) Problem() int { return e.problem }
```

should be preferred to

```go
type DataError struct {
    Problem int
    Inner   error
}
```

then you'll have to sell me on it. because I don't buy it 😜 Why? And why does mutability play? 

—

>  I think a more common case is to do something like . . .

I've never seen this in practice, and wouldn't call it common. But I guess I don't see anything wrong with it, sure — except that error types should always be defined on pointer rather than value receivers.

**Comment by mway** [comment]
> Why? And why does mutability play?

We haven't solidified our stance here yet (I should have qualified the original statement with that, apologies), but I think of errors similar to context values: the fact that they are different types of objects notwithstanding, you create _derivative_ contexts when you need to modify its data (unless you're abusing pointers), and I think the same should apply to errors.

The primary reason is because it allows for extremely easy (unintentional or otherwise) obfuscation/shadowing of errors, enabling changes in their state that does not map to stack traces. You could conceivably completely change the data or semantics of an error mid-handling, then propagate your changes completely transparently (a la hijacking), whereas wrapping the error maintains unwrappability and some notion of error hierarchy.

Again, there is some debate to be had about this, but in lieu of a convincing counter-example, I think "safety and correctness first" is a better starting point than "directly manipulate all errors because why not". Would be interested in a reasonable, commonplace real-world example of why it would be valuable to handle custom errors in this way.

**Comment by peterbourgon** [comment]
> You create derivative contexts when you need to modify its data (unless you're abusing pointers), and I think the same should apply to errors . . . 

Errors are just values, like ints or http.Clients or anything else. There's nothing special about them.

If you want to establish an error hierarchy, sure! If it serves some purpose for your users, go for it. If you want to make them unwrappable, or not unwrappable, or map them to HTTP status codes, or embed domain information in them, great. Whatever works.

So like

> Would be interested in a reasonable, commonplace real-world example of why it would be valuable to handle custom errors in this way.

doesn't really make sense to me.

Concretely: all code should default to yielding wrapped (and unwrappable) errors, with annotation, via fmt.Errorf.

```go
func Exported() error {
    x, err := something()
    if err != nil {
        return fmt.Errorf("somthing: %w", err)
    }
```

Obscuring inner errors via `%v` serves little purpose — concrete error types aren't part of your API in a compatibility sense unless you say that they are, so it only serves to hide information from users. You can do it, but as an exception rather than a rule.

This is the default because it's rare that callers can actually make meaningful decisions based on any specific details of returned errors. Usually, like 90% of the time, all received errors are equivalent — the thing you tried to do failed, and so you have to give up. If that's not the case, then the next step up the complexity ladder is to define and yield sentinel errors.

```go
func Exported() error {
    x, err := something()
    if err != nil {
        return ErrNotFound
    }
```

Callers can use errors.Is to program against error identity, which is often all that's necessary, and a hugely better user experience than errors.As. But in the _extraordinarily rare_ cases where callers can make meaningful use of error details beyond their identity, then it's appropriate to define and return error types.

```go
type BadError struct {
    Code  int
    Inner error
}

func (e *BadError) Error() string  { ... }
func (e *BadError) Unwrap() error { ... }

func Exported() error {
    x, err := something()
    if err != nil {
        return &BadError{Code: 123, Inner: err}
    }
```

Error values like this — which, to be totally clear, are extraordinarily rare — are just values. Callers (must) check for them via errors.As. Why does mutability matter? idgi

**Comment by peterbourgon** [comment]
> enabling changes in their state that does not map to stack traces. 

That's right. Errors are not related to stack traces, any more than an instance of any other type. Errors aren't exceptions, right? It's incoherent to bundle stack traces into errors, because errors should always be handled in situ, at the point of reception. Or do I misunderstand your point?
