### ISSUE TITLE
About updating uber-go-style-guide-kr 

### ISSUE THREAD

**Issue by Yupjun** [uber-go/guide#142]
Hi all

The Korean version of uber-go-style-guide has not been updated for 9 months. 
There have been many updates to the current English version of the uber-go-style guide, 
and I think the Korean translation does not fully reflect the current version. 
If you don't mind, I wonder if I can translate the latest version of uber-go-style-guide and share it on Github.

https://github.com/TangoEnSkai/uber-go-style-guide-kr/issues/8

**Comment by sywhang** [comment]
Hey there, sure. Thanks for volunteering to do the work.

I also had some qualms about the translation of the section on functional options, but will follow up about that separately in the community translation repo.

**Comment by TangoEnSkai** [comment]
Sorry to comment late.

 I have been a long vacation, and recently restart updating the contents and translation up to date. 

Like other contributors of the Korean translation repo, 
we welcome anyone make PRs proactively updating the contents, 
otherwise I will take care all translation with some people who are interested in.

In addition, we will think about improving better contribution guidelines in the repo.
