### ISSUE TITLE
consider three groups of import group ordering

### ISSUE THREAD

**Issue by chenzhiwei** [uber-go/guide#28]
```
import (
  "fmt"
  "os"

  // third party packages
  "go.uber.org/atomic"
  "golang.org/x/sync/errgroup"

  // project packages
  "github.com/user/project"
)
```

**Comment by abhinav** [comment]
Hello! We previously did recommend three import groups, but the ordering was:
standard library, project packages, and third party packages.

We switched away from that recommendation because,

1. The tooling we had at the time did not automatically handle the grouping.
2. Imports were sorted alphabetically so project packages got grouped together
   regardless.
3. The definition of what constituted a project was unclear. For most cases it
   was a single repository, but not for mega-repos that consisted of multiple
   independent projects.

I'll admit that none of these reasons are iron-clad and can be argued further.
Especially the last one, which loses some ground to Go modules: a project is a
single module, and a repository may have multiple.

That said, we do not see a lot of benefit to changing the recommendation at
this time compared to the cost of changing it.

**Comment by prashantv** [comment]
Here's a related [issue we filed](https://github.com/golang/go/issues/27673) about import group ordering in the past.

While `goimports` does support `-local` to support multiple groups, it requires:
 * Figuring out what the "project" should be as @abhinav mentioned earlier. With `go.mod`, it's a little clearer now, but this was a source of confusion in the past.
 * Passing in the `-local` flag explicitly on any invocation of `goimports`. This becomes a lot trickier with IDE integrations when used with many projects.

We settled on the current recommendation as it was enforced by tooling, didn't need any custom `goimports` arguments per-project, and was easy to reason about.

**Comment by abhinav** [comment]
Closing since the discussion has been resolved.

**Comment by chenyanchen** [comment]
I support third party packages sort by standard library, dependencies, project.
```
1. Standard library first.
2. Dependencies means open source package + closed source package.
3. Project: just current project, current `go.mod` package.
```
I see the important things is you should show your respect to the open source and dependencies.
