### ISSUE TITLE
Lack of IntelliJ/Goland support for Table Driven Tests

### ISSUE THREAD

**Issue by styeung** [uber-go/guide#32]
Given the lack of IntelliJ/Goland support for Table Driven Tests (and by support, I mean the ability to run tests individually from within the IDE), I feel like the recommendation for table driven tests feels premature.

Instead of Table Driven Tests, how about something like this:

```go
func TestSplitHostPort_Full(t *testing.T) {
	give := "192.0.2.0:8000"
	wantHost := "192.0.2.0"
	wantPort := "8000"

	testSplitHostPort(t, give, wantHost, wantPort)
}

func TestSplitHostPort_NoHost(t *testing.T) {
	give := ":8000"
	wantHost := ""
	wantPort := "8000"

	testSplitHostPort(t, give, wantHost, wantPort)
}

func testSplitHostPort(t *testing.T, give string, wantHost string, wantPort string) {
	host, port, err := net.SplitHostPort(give)
	require.NoError(t, err)
	assert.Equal(t, wantHost, host)
	assert.Equal(t, wantPort, port)
}
```

**Comment by shyiko** [comment]
Custom `Edit Configuration...` -> `Pattern` can be used to run individual sub-test(s) (e.g. changing `^TestExample$` to `^TestExample$/^A$` will run A sub-test of TestExample but not B). Not as convenient but it is technically supported.

**Comment by jeffbean** [comment]
Also having a style informed on IDE limitations is not a good feedback loop.

**Comment by abhinav** [comment]
Hey, Thanks for the workaround @shyiko.

@styeung, I disagree that this recommendation is premature. Table tests have
been a recommendation from the Go community since Go 1.0, and have been part
of Uber's Go Style Guide from pretty early on.

For reference, here's a [talk from 2012][1] that references table tests, and a
[blog post from 2013 by Dave Cheney][2] on the same topic.

[1]: https://talks.golang.org/2012/10things.slide#3
[2]: https://dave.cheney.net/2013/06/09/writing-table-driven-tests-in-go

Subtests were added in [Go 1.7 in 2016][3]. That IDEs don't yet fully support
subtests does not seem like a strong-enough reason to discourage use of a
widely accepted best-practice.

[3]: https://golang.org/doc/go1.7#testing

**Comment by prashantv** [comment]
Also see https://github.com/golang/go/wiki/TableDrivenTests

I agree that it's as easy to run a single test case, but it makes it easier to compare test-cases, and separates the input for the test from the execution logic.

**Comment by abhinav** [comment]
Closing since this discussion is resolved.
